# Generated by Django 4.1.4 on 2022-12-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='content',
            field=models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend')], default='BE', max_length=2),
        ),
    ]
