# Generated by Django 4.1.4 on 2023-01-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_404',
            field=models.BooleanField(default=False),
        ),
    ]
