# Generated by Django 4.1.4 on 2023-01-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='content',
        ),
    ]
