# Generated by Django 4.1.4 on 2023-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
