# Generated by Django 4.1.4 on 2023-03-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_homework_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkdetail',
            options={'ordering': ('pk',)},
        ),
    ]
