# Generated by Django 4.1.4 on 2023-01-14 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='TEST', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
