# Generated by Django 4.1.4 on 2023-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_name_video_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='release_date',
            field=models.DateField(),
        ),
    ]
