# Generated by Django 4.1.4 on 2023-01-14 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_name_alter_video_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
