# Generated by Django 4.1.4 on 2023-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_forgotpasswordmodel_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
