# Generated by Django 4.1.4 on 2023-01-23 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usertoken_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=39)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
