# Generated by Django 4.1.4 on 2023-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/media/photos'),
        ),
    ]
